# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'musicapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for musicapp
  
  rn_path = '../node_modules/react-native'
    
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'RCTBlob',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod 'IQKeyboardManager'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBSDKCoreKit', '~> 4.37.0'
  pod 'FBSDKLoginKit', '~> 4.37.0'
  pod 'FBSDKShareKit', '~> 4.37.0'
  
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  pod 'GoogleSignIn', '~> 4.4.0'
  
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Core', '~> 5.20.1'
  
  pod 'TwitterKit', '~> 3.3.0'
  pod 'react-native-twitter-signin', :path => '../node_modules/react-native-twitter-signin'
  
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  
  pod 'Fabric'
  pod 'Crashlytics'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
